# Development

services:
  appserver:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: /start.sh
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
